### ISSUE TITLE
Trimou not working. Just numbers as output.

### ISSUE THREAD

**Issue by mpetzold** [trimou/trimou#71] opened 2015-07-30 06:34 UTC
I have tried to use Trimou, but it is absolutely not working. Even with the simplest example from the webpage the delimiters are just replaced with very long numbers. This is also the case for my other attempts using a java.util.Map as context.

Example:

String data = "Hello world!";
String template = "{{this}}";
MustacheEngine engine = MustacheEngineBuilder.newBuilder().build();
Mustache mustache = engine.compileMustache("myTemplateName", template);
String output = mustache.render(data);

Output:

721011081081113211911111410810033

We are using Java SE 1.7 on Mac OS and Windows 7.

**Comment by mkouba** [comment] 2015-07-30 06:41
Hi @mpetzold,
what version of trimou are you using? Could you post the full source of your test? Also does the simple example [1] work for you?

[1]
https://github.com/trimou/trimou/blob/master/examples/simple/src/main/java/org/trimou/example/simple/SimpleExample.java

**Comment by mpetzold** [comment] 2015-07-30 08:00
I have tested several versions down to 1.6.2. As I said it is also the same on another machine running Windows and most probably different version of Java. I really want to use the Map and not items.

I actually posted the full source, only missing the "System.out.println(data);"

**Comment by mkouba** [comment] 2015-07-30 08:32
`System.out.println(data)`? You mean `System.out.println(output)`, right? Anyway, that's odd. I must admit we don't run the test suite on windows and mac os. I'll have to get some windows machine and run the build.

**Comment by mpetzold** [comment] 2015-07-30 08:34
Yes, output of course. Sorry.

**Comment by mkouba** [comment] 2015-07-31 10:33
I was able to run the build on a Windows 7 machine with Oracle JDK 8u51. The test suite passed (except for few intermittent failures in PrettyTime extension which should be fixed now).

Could you share the source code of your test? (github repo, upload attachment, etc.)

**Comment by loucasa** [comment] 2015-07-31 11:28
I have the same problem (also running on mac os), seems setting this stops it but not a solution:
            .setProperty(EngineConfigurationKey.SKIP_VALUE_ESCAPING, false)

**Comment by mkouba** [comment] 2015-07-31 11:37
@loucasa that's interesting. The `org.trimou.engine.text.DefaultTextSupport` responsible for escaping is using `org.apache.commons.lang3.StringEscapeUtils`. You could try to supply your own escaping logic, i.e. using `com.google.common.html.HtmlEscapers.htmlEscaper()` if available. See also http://trimou.org/doc/latest.html#text_support

**Comment by loucasa** [comment] 2015-07-31 13:03
Ahh, seems the problem is in StringEscapeUtils, I had a dependency on commons-lang3 version 3.4, if I change it to 3.3 the problem dissapears

**Comment by mpetzold** [comment] 2015-07-31 17:33
I am also using org.apache.commons.lang3 v3.4.0.

**Comment by mkouba** [comment] 2015-07-31 19:50
This might be related: https://issues.apache.org/jira/browse/LANG-877

**Comment by mpetzold** [comment] 2015-08-01 08:41
Thanks for the workaround. Switching to version 3.3.2 of commons.lang3 works well :)!

**Comment by mkouba** [comment] 2015-08-03 07:08
For the record: commons-lang3 v3.4 does not work on Linux either. I will investigate the issue and report a bug if appropriate.

**Comment by mkouba** [comment] 2015-08-03 07:42
In fact, there is a bug in `org.trimou.util.StringBuilderWriter`. The aforementioned performance improvement seems to be legal. This will be fixed in 1.8.1 (release planned for the next week).

**Comment by mkouba** [comment] 2015-08-03 12:55
@mpetzold @loucasa It would be great if you could test the master branch with your application using commons-lang3 v3.4.

**Closed by mkouba** 2015-08-03 12:55 UTC
Labels: bug

**Comment by loucasa** [comment] 2015-08-04 11:17
will try if I get some time today

Date: Mon, 3 Aug 2015 05:55:53 -0700

**Comment by loucasa** [comment] 2015-08-05 08:44
Works for me against master, thanks

**Comment by mkouba** [comment] 2015-08-05 09:00
@loucasa Thanks for verification!

**Comment by mkouba** [comment] 2015-08-15 08:04
@loucasa @mpetzold Trimou [1.8.1](https://github.com/trimou/trimou/releases/tag/1.8.1.Final) has been released. It will take some time to sync with Maven central though...
